---
title: "README"
author: "Oriol Gracia, Júlia Mir, Helena Rodriguez"
date: "February 26th, 2018"
output: pdf_document
---
#Naive Bayes model to classify tissue types and brain regions using splicing patterns

##Introduction

We have created a package to use data from GTEX to predict the type of tissue from a given sample based on whether the splicing events take place or not.

Here you can find a brief explanation of every program in our pipeline, in the same order in which they should be used, and also some examples.

## INDEX

1. Problem Solution

2. Dependencies of R

3. Pipeline

## 1. Problem Solution

In this package we provide a script that runs the Naive bayes prediction algorithm for each one of the
problems presented in class.

These scripts use as input data files which are already processed. (The best splicings has already been
selected and the sampling process has already been done).

This is done in order to miniminize time, because the data parsing and splicing selection is slower than the prediction
part.

However, we provide all the necessary scripts to run the whole process, if you want to use them just check
the pipe line section.

Usage of the examples:

Brain exercise:

python3 Naive_prediction.py -t sample_data/Filtered60_train_brain.txt -s sample_data/Filtered60_test_brain.txt
-o output_file.txt

Tissue exercise:

python3 Naive_prediction.py -t sample_data/Filtered60_train_tissue.txt -s sample_data/Filtered60_test_tissue.txt
-o output_file.txt

In the terminal the % of correct guesses will be printed, and in the output file all the predictions will be
shown.

## 2. Dependencies of R

To run the provided R script you need the following packages:

-
-
-
-

## 3. Pipeline

This is a short explanation of the pipeline used and what each script does. A more detailed explanation
can be found in the documentation of each script.

##Pre-processing your data
The first thing is to preprocess our data, which can be done using three different scripts:  
  
- **transforming_rawdata.py**: This first script allows you to transform GTEX IDs into more manageable IDs, like tissue names.  
*Usage*: It needs three attributes, the GTEX header description (the new IDs), the GTEX input fie (your data), and the name of the output file.  
  
- **NA_processer.py**: This script allows you to analyse how many NA your data have, how they are distributed among your splicing sites and, if you wish to, remove those with a high ratio of NA.  
*Usage*: It needs "-i output_file_from_the_previous_script", "-o output_prefix_name" (this is the prefix added to the output files name created by this script) and, optionally, "-r NA_ratio_to_remove" (if provided, removes all splicing sites with that NA ratio or higher).  

  
- **remove_column.py**: Finally, this script doesn't need to be used always. It is made in case you need to remove one of your sample tissue types (e.g., in case you do not have enough samples) (one column per time).  
*Usage*: It requires three arguments, input_file_name, output_file_name and columns_name_to_remove.  

##Sampling
Divide your data set into two separate sets, training and testing.  
  
- **Sampling.py**: Divides your data set into the two groups.  
*Usage*: This script has four arguments: -i input_file (output from NA_processer or remove_column), -t output_file_training_set, -s output_file_testing_set, and -z number_of_elements (for training per tissue). If you provide a higher -z than tissue types, it will raise and error.  

##Training and testing data
- **Gtex_Loader.py**: It includes three functions to be used in further scripts, not used by the user. Transforms data so it can be used later.  
  
- **Splicing_analyzer.py**: Analyses the entropy and information gain (or mutual information). It also removes redundant splicing sites, and finally uses a function from Gtex_Loader to create a document with the final training data (with only the useful splicings).    
*Usage*: It requires two arguments, input_file and output_file. It also uses the outputs from Gtex_Loader.py.  
  
- **Gtex_Naive_Bayes.py**: Main script of the project, not meant to be used alone. It has several
functions inside:
  - One for the training of the model (training())
  - One to calculate the score for the sample to be each one of the tissues (score_all())
  - One to produce a file with all the scores to make the roc curves (thresholds())
  - One for making the predictions(predict())
  
More information can be found on the script documentation.

##Quality assessment

- **ROC_data.py**: Calculates the TPR and FPR per tissue or in total. Returns data in an R-friendly format.   
*Usage*: It requires an input_file, which can be a list of N file names (output from Gtex_Naive_Bayes.py). The file name MUST be the name of the tissue.
